on:
  push:
    branches:
      - dev
    paths:
      - "services/payment-service/**"
      - ".github/workflows/payment-service.yaml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd services/payment-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10 (preview)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: preview

      - name: Restore dependencies
        run: |
          cd services/payment-service
          dotnet restore

      - name: Build
        run: |
          cd services/payment-service
          dotnet build --no-restore

      - name: Run tests
        run: |
          cd services/payment-service
          dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install hostflow ./helm/charts/payment-service \
            --namespace default \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/payment-service \
            --set image.tag=latest \
            --set image.pullPolicy=Always \
            --set actualSecrets.STRIPE_API_KEY="${{ secrets.STRIPE_KEY }}" \
            --set actualSecrets.DATABASE_URL="${{ secrets.DB_URL_PAYMENT }}" \